name: cma-aws
version: 0.1.4
description: The Cluster Manager API AWS Helper
keywords:
- hybridstack
- api
home: https://github.com/samsung-cnct/cma-aws
sources:
- https://github.com/samsung-cnct/cma-aws
maintainers:
- name: Michael Venezia
  email: mvenezia@gmail.com
icon: https://github.com/samsung-cnct/solas/docs/images/samsung-logo.svg
engine: gotpl
